stages:
  - lint
  - build
  - deploy

.linux_before:
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  dependencies: []
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_MAXSIZE: "32G"
    CCACHE_COMPRESS: "1"
    CCACHE_SLOPPINESS: "include_file_ctime,pch_defines,time_macros,file_macro,system_headers"
    CCACHE_NOHASHDIR: "1"
    CCACHE_DIR: "/cache/ccache"
    BUILD_TYPE: "Release"
    SIGHT_BUILD_DOC: "ON"
    CC: "/usr/lib/ccache/gcc-10"
    CXX: "/usr/lib/ccache/g++-10"
  before_script:
    # Prepare sight source
    - sudo chown -R sight:sight .
    - mkdir -p $CI_PROJECT_DIR/.install $CI_PROJECT_DIR/.build
    # git configuration
    - git config merge.renameLimit 999999
    - git config user.name ${GITLAB_USER_ID}
    - git config user.email ${GITLAB_USER_EMAIL}
    - git config advice.addIgnoredFile false
    # Merge the MR branch into dev.
    - >
      if [ -z "$CI_COMMIT_TAG" ] && [ "$CI_COMMIT_REF_NAME" != "dev" ] && [ "$CI_COMMIT_REF_NAME" != "master" ]; then
        git fetch --all
        git checkout dev
        git reset --hard origin/dev
        git merge "origin/"${CI_COMMIT_REF_NAME} --no-commit --no-ff
        export EXTRA_BRANCH="dev"
      else
        export EXTRA_BRANCH="${CI_COMMIT_REF_NAME}"
      fi
    # Reset the modified time of all files to improve ccache performance
    - /usr/lib/git-core/git-restore-mtime --force --skip-missing --commit-time

lint:sheldon:
  extends: .linux_before
  dependencies: []
  stage: lint
  script:
    # Download sheldon.
    # TODO: use dev/master/tag branch
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ircad.fr/Sight/sight-git.git -b ${EXTRA_BRANCH} $CI_PROJECT_DIR/.build/sight-git
    # Stage all files from the merge to get them checked by sheldon.
    - git add *
    # Display modified files.
    - git status
    # Run sheldon on the merge result.
    - .build/sight-git/hooks/sheldon
  except:
    - dev
    - master
    - tags

.linux_build:
  extends: .linux_before
  dependencies: []
  stage: build
  script:
    # Print CCache statistics
    - ccache -s
    # Launch CMake
    - cd $CI_PROJECT_DIR/.build
    - >
      cmake $CI_PROJECT_DIR
      -G Ninja
      -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/.install
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DSIGHT_BUILD_TESTS=ON
      -DSIGHT_BUILD_DOC=${SIGHT_BUILD_DOC}
      -DSIGHT_ENABLE_PCH=OFF
      -DSIGHT_DEPS_ROOT_DIRECTORY=/cache/.sight-deps
      -DSIGHT_ENABLE_OPENVSLAM=ON
    # Touch all generated files to improve CCache performance
    - find . -type f -iname '*.?pp' -exec touch -t 197001010000 {} \;
    # Build
    - ninja
    # Print CCache statistics (Cache hit rate should have raised)
    - ccache -s
    # Clone sight-data.
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ircad.fr/Sight/sight-data.git -b ${EXTRA_BRANCH}
    - export FWTEST_DATA_DIR=$CI_PROJECT_DIR/.build/sight-data
    # Launch tests
    - ctest --timeout 480 --output-on-failure -O ctest.log -j4
    # Build documentation if needed
    - >
      if [ "${SIGHT_BUILD_DOC}" == "ON" ]; then
        ninja doc
      fi

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/.build/ctest.log
      - $CI_PROJECT_DIR/.build/Documentation/Doxygen/

build:linux-debug-gcc:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Debug"
    SIGHT_BUILD_DOC: "OFF"
    CC: "/usr/lib/ccache/gcc-10"
    CXX: "/usr/lib/ccache/g++-10"

build:linux-release-gcc:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Release"
    SIGHT_BUILD_DOC: "ON"
    CC: "/usr/lib/ccache/gcc-10"
    CXX: "/usr/lib/ccache/g++-10"

build:linux-debug-clang:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Debug"
    SIGHT_BUILD_DOC: "OFF"
    CC: "/usr/lib/ccache/clang-11"
    CXX: "/usr/lib/ccache/clang++-11"

build:linux-release-clang:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Release"
    SIGHT_BUILD_DOC: "OFF"
    CC: "/usr/lib/ccache/clang-11"
    CXX: "/usr/lib/ccache/clang++-11"


.windows_before:
  dependencies: []
  variables:
    BUILD_TYPE: "Release"
  before_script:
    # Merge the branch into dev.
    - set EXTRA_BRANCH=%CI_COMMIT_REF_NAME%
    - >            
      if "%CI_COMMIT_REF_NAME%" NEQ "dev" (
        if "%CI_COMMIT_REF_NAME%" NEQ "master" (
          if "%CI_COMMIT_TAG%" EQU "" (
            git config user.name ${GITLAB_USER_ID}
            git config user.email ${GITLAB_USER_EMAIL}
            git fetch --all
            git checkout dev
            git reset --hard origin/dev
            git merge "origin/"%CI_COMMIT_REF_NAME% --no-commit --no-ff
            set EXTRA_BRANCH=dev
          )
        )
      )
    - if not exist "%CI_PROJECT_DIR%/install" md "%CI_PROJECT_DIR%/install"
    - if not exist "%CI_PROJECT_DIR%/build" md "%CI_PROJECT_DIR%/build"
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
    - chcp 1252
  tags:
    - shell
    - windows

.windows_build:
  extends: .windows_before
  dependencies: []
  stage: build
  script:
    # Build the project on the merge result.
    - cd "%CI_PROJECT_DIR%/build"
    - dir "%CI_PROJECT_DIR%/cmake/build"
    # Checkout vcpkg packages
    - call "C:\Program Files\CMake\bin\cmake" -DOUTPUT="C:\Cache" -P "%CI_PROJECT_DIR%\cmake\build\vcpkg.cmake"
    - >
      call "C:\Program Files\CMake\bin\cmake" %CI_PROJECT_DIR%
      -G Ninja
      -DCMAKE_TOOLCHAIN_FILE=C:\Cache\sight-vcpkg\scripts\buildsystems\vcpkg.cmake
      -DCMAKE_INSTALL_PREFIX=%CI_PROJECT_DIR%/install
      -DCMAKE_BUILD_TYPE=Debug
      -DSIGHT_BUILD_TESTS=ON
      -DSIGHT_BUILD_DOC=OFF
      -DSIGHT_ENABLE_PCH=OFF
    - ninja
    # Run unit tests.
    #- git clone --depth 1 https://gitlab-ci-token:%CI_JOB_TOKEN%@git.ircad.fr/Sight/sight-data.git -b "%EXTRA_BRANCH%"
    #- set FWTEST_DATA_DIR=%CI_PROJECT_DIR%\build\sight-data
    #- ctest --timeout 480 --output-on-failure -O ctest.log -E fwRenderOgreTest -j4
  artifacts:
    when: always
    name: "%CI_JOB_NAME%-%CI_COMMIT_REF_SLUG%"
    paths:
      - build/ctest.log
      - build/fwTest.log

build:windows-debug:
  extends: .windows_build
  variables:
    BUILD_TYPE: "Debug"

deploy:pages:
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  stage: deploy
  dependencies:
    - build:linux-release-gcc
  script:
    - mv .build/Documentation/Doxygen/html/ public/
  artifacts:
    paths:
      - public
  only:
    - dev
